In [ ]:
import pandas as pd 
import numpy as np

In [2]:
import pandas as pd

df=pd.read_csv('Forecast.csv', encoding='cp949')

df.head()

     연도   월       연월 수출입구분 수출입구분설명        물동량
0  2003   2  2003-02    OT    수출환적  161074.50
1  2003  11  2003-11    IT    수입환적  170733.50
2  2006   1  2006-01    OT    수출환적  203348.25
3  2018   1  2018-01    OO      수출  413797.75
4  2013   6  2013-06    OO      수출  389650.25

In [53]:
print(df.shape)
print(df.columns.to_list())
print(df.dtypes)
print(df.info())
print(df.describe())

(31, 15)
['년도', '합계', '자성대부두', '신선대부두', '감만부두', '우암부두', '감천한진', '신감만부두', '일반부두', '신항1부두', '신항2부두', '신항3부두', '신항4부두', '신항5부두', '다목적부두등']
년도        int64
합계        int64
자성대부두     int64
신선대부두     int64
감만부두      int64
우암부두      int64
감천한진      int64
신감만부두     int64
일반부두      int64
신항1부두     int64
신항2부두     int64
신항3부두     int64
신항4부두     int64
신항5부두     int64
다목적부두등    int64
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   년도      31 non-null     int64
 1   합계      31 non-null     int64
 2   자성대부두   31 non-null     int64
 3   신선대부두   31 non-null     int64
 4   감만부두    31 non-null     int64
 5   우암부두    31 non-null     int64
 6   감천한진    31 non-null     int64
 7   신감만부두   31 non-null     int64
 8   일반부두    31 non-null     int64
 9   신항1부두   31 non-null     int64
 10  신항2부두   31 non-null     int64
 11  신항3부두   31 non-null     int64
 12  신항4부두   31 non-null     int64
 13  신항5부두   31 non-null     int64
 14  다목적부두등  31 non-null     int64
dtypes: int64(15)
memory usage: 3.8 KB
None
             년도             합계         자성대부두         신선대부두          감만부두  \
count    31.000         31.000        31.000        31.000        31.000
mean  2,009.000 13,968,781.839 1,593,494.387 1,913,993.613 1,560,014.161
std       9.092  6,999,840.852   534,312.037   702,625.486   818,635.394
min   1,994.000     48,140.000         0.000         0.000         0.000
25%   2,001.500  8,763,491.500 1,404,957.000 1,471,135.500 1,229,097.500
50%   2,009.000 13,454,506.000 1,729,414.000 2,054,646.000 1,498,394.000
75%   2,016.500 19,981,102.000 1,920,802.000 2,388,699.500 1,999,389.000
max   2,024.000 24,402,022.000 2,275,402.000 2,813,335.000 2,862,251.000

             우암부두        감천한진         신감만부두          일반부두         신항1부두  \
count      31.000      31.000        31.000        31.000        31.000
mean  274,748.871 174,349.484   750,659.968 1,291,685.581 1,123,327.839
std   260,821.050 237,488.157   485,674.603 1,102,135.980 1,169,519.214
min         0.000       0.000         0.000    48,140.000         0.000
25%       433.500     623.000   234,139.500   304,167.000         0.000
50%   316,902.000   1,880.000   976,348.000   678,177.000   701,124.000
75%   540,690.000 441,369.000 1,126,288.000 2,575,833.500 2,419,781.000
max   640,339.000 574,824.000 1,250,360.000 3,202,849.000 3,018,315.000

              신항2부두         신항3부두         신항4부두         신항5부두        다목적부두등
count        31.000        31.000        31.000        31.000        31.000
mean  2,123,785.742 1,238,135.935 1,027,237.548   767,662.226   129,686.484
std   2,238,415.343 1,285,070.893 1,118,048.373 1,002,711.544   359,132.660
min           0.000         0.000         0.000         0.000         0.000
25%           0.000         0.000         0.000         0.000         0.000
50%     796,830.000   922,419.000         0.000         0.000       214.000
75%   4,578,868.500 2,511,853.500 2,202,690.500 1,740,969.000    50,448.500
max   5,501,091.000 3,076,160.000 2,560,274.000 2,496,909.000 1,844,868.000

In [87]:
df.describe()

,항구명,외내항구분,수출입구분,입출항구분상세,1999,Unnamed: 5,Unnamed: 6,2000,Unnamed: 8,Unnamed: 9,...,Unnamed: 78,2024,Unnamed: 80,Unnamed: 81,2025,Unnamed: 83,Unnamed: 84,전년대비율(%),Unnamed: 86,Unnamed: 87
count,48,48,47,46,47,47,47,46,46,46,...,47,40,40,40,47,47,47,43,41,40
unique,4,3,4,5,35,35,35,35,35,35,...,38,29,29,29,38,35,34,32,32,31
top,합계,외항,연안,출항,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
freq,12,28,15,18,5,5,5,4,4,4,...,4,8,8,8,4,6,7,11,9,8

In [90]:
pd.DataFrame({
    '자료형': df.dtypes.astype('str'),
    '비결측 수': df.notna().sum(),
    '결측 수': df.isna().sum(),
    '결측률(%)': df.isna().mean()*100,
    '고유값 수': df.nunique(dropna=True)

})

             자료형  비결측 수  결측 수  결측률(%)  고유값 수
연도         int64   1376     0   0.000     34
월          int64   1376     0   0.000     12
연월           str   1376     0   0.000    398
수출입구분        str   1376     0   0.000      4
수출입구분설명      str   1376     0   0.000      4
물동량      float64   1376     0   0.000   1374

In [3]:
import pandas as pd

df=pd.read_csv('Status.csv', encoding='cp949')

df.head()

     연도   컨물동량   증감율  수출입소계    수입    수출   환적소계  환적점유율  환적증감율
0  2013  17686  3.75   8934  4424  4509   8748  49.47   7.38
1  2014  18683  5.64   9254  4596  4658   9429  50.47   7.78
2  2015  19469  4.20   9364  4714  4650  10105  51.91   7.17
3  2016  19456 -0.06   9620  4801  4819   9836  50.55  -2.67
4  2017  20493  5.33  10186  5042  5144  10225  49.90   3.96

In [18]:
print(df.shape)
print(df.columns.to_list())
print(df.dtypes)
print(df.info())
print(df.describe())

(13, 9)
['연도', ' 컨물동량', '증감율', '수출입소계', '수입', '수출', '환적소계', '환적점유율', '환적증감율']
연도         int64
 컨물동량      int64
증감율      float64
수출입소계      int64
수입         int64
수출         int64
환적소계       int64
환적점유율    float64
환적증감율    float64
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   연도      13 non-null     int64
 1    컨물동량   13 non-null     int64
 2   증감율     13 non-null     float64
 3   수출입소계   13 non-null     int64
 4   수입      13 non-null     int64
 5   수출      13 non-null     int64
 6   환적소계    13 non-null     int64
 7   환적점유율   13 non-null     float64
 8   환적증감율   13 non-null     float64
dtypes: float64(3), int64(6)
memory usage: 1.0 KB
None
               연도          컨물동량        증감율         수출입소계           수입  \
count    13.00000     13.000000  13.000000     13.000000    13.000000
mean   2019.00000  21422.153846   2.991538  10071.230769  5014.000000
std       3.89444   2169.439707   2.770773    625.806966   310.466048
min    2013.00000  17686.000000  -2.770000   8934.000000  4424.000000
25%    2016.00000  19469.000000   1.520000   9620.000000  4801.000000
50%    2019.00000  21824.000000   4.040000  10233.000000  5117.000000
75%    2022.00000  22706.000000   5.330000  10433.000000  5208.000000
max    2025.00000  24882.000000   5.700000  10904.000000  5409.000000

                수출          환적소계      환적점유율      환적증감율
count    13.000000     13.000000  13.000000  13.000000
mean   5057.076923  11343.846154  52.768462   4.395385
std     317.513638   1591.690864   2.233655   4.459913
min    4509.000000   8748.000000  49.470000  -4.130000
25%    4819.000000  10105.000000  50.550000   2.100000
50%    5144.000000  11638.000000  52.920000   4.400000
75%    5225.000000  12273.000000  54.050000   7.380000
max    5495.000000  14097.000000  56.700000  11.770000

In [23]:
df.describe()

,연도,컨물동량,증감율,수출입소계,수입,수출,환적소계,환적점유율,환적증감율
count,13.00000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000,13.000000
mean,2019.00000,21422.153846,2.991538,10071.230769,5014.000000,5057.076923,11343.846154,52.768462,4.395385
std,3.89444,2169.439707,2.770773,625.806966,310.466048,317.513638,1591.690864,2.233655,4.459913
min,2013.00000,17686.000000,-2.770000,8934.000000,4424.000000,4509.000000,8748.000000,49.470000,-4.130000
25%,2016.00000,19469.000000,1.520000,9620.000000,4801.000000,4819.000000,10105.000000,50.550000,2.100000
50%,2019.00000,21824.000000,4.040000,10233.000000,5117.000000,5144.000000,11638.000000,52.920000,4.400000
75%,2022.00000,22706.000000,5.330000,10433.000000,5208.000000,5225.000000,12273.000000,54.050000,7.380000
max,2025.00000,24882.000000,5.700000,10904.000000,5409.000000,5495.000000,14097.000000,56.700000,11.770000

In [12]:
pd.DataFrame({
    '자료형': df.dtypes.astype('str'),
    '비결측 수': df.notna().sum(),
    '결측 수': df.isna().sum(),
    '결측률(%)': df.isna().mean()*100,
    '고유값 수': df.nunique(dropna=True)

})

           자료형  비결측 수  결측 수  결측률(%)  고유값 수
연도       int64     13     0     0.0     13
 컨물동량    int64     13     0     0.0     13
증감율    float64     13     0     0.0     13
수출입소계    int64     13     0     0.0     13
수입       int64     13     0     0.0     13
수출       int64     13     0     0.0     13
환적소계     int64     13     0     0.0     13
환적점유율  float64     13     0     0.0     13
환적증감율  float64     13     0     0.0     13

# 환적

환적점유율은 전체 물동량의 약 50% 수준
환적 물동량은 전반적으로 증가 추세이며, 전체 컨테이너 물동량의 약 절반을 차지하는 핵심 물동량이다.

In [30]:
df=pd.read_csv('container.csv')
df.head()

,년도,합계,자성대부두,신선대부두,감만부두,우암부두,감천한진,신감만부두,일반부두,신항1부두,신항2부두,신항3부두,신항4부두,신항5부두,다목적부두등
0,1994,48140,0,0,0,0,0,0,48140,0,0,0,0,0,0
1,1995,59775,0,622,0,0,0,0,59153,0,0,0,0,0,0
2,1996,4809217,1673341,1302513,0,21171,0,0,1812192,0,0,0,0,0,0
3,1997,5246646,1757757,1413847,23,316902,11848,0,1746269,0,0,0,0,0,0
4,1998,5701360,1096650,1121949,891424,281571,348910,0,1960856,0,0,0,0,0,0

In [31]:
print(df.shape)
print(df.columns.to_list())
print(df.dtypes)
print(df.info())
print(df.describe())

(31, 15)
['년도', '합계', '자성대부두', '신선대부두', '감만부두', '우암부두', '감천한진', '신감만부두', '일반부두', '신항1부두', '신항2부두', '신항3부두', '신항4부두', '신항5부두', '다목적부두등']
년도        int64
합계        int64
자성대부두     int64
신선대부두     int64
감만부두      int64
우암부두      int64
감천한진      int64
신감만부두     int64
일반부두      int64
신항1부두     int64
신항2부두     int64
신항3부두     int64
신항4부두     int64
신항5부두     int64
다목적부두등    int64
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   년도      31 non-null     int64
 1   합계      31 non-null     int64
 2   자성대부두   31 non-null     int64
 3   신선대부두   31 non-null     int64
 4   감만부두    31 non-null     int64
 5   우암부두    31 non-null     int64
 6   감천한진    31 non-null     int64
 7   신감만부두   31 non-null     int64
 8   일반부두    31 non-null     int64
 9   신항1부두   31 non-null     int64
 10  신항2부두   31 non-null     int64
 11  신항3부두   31 non-null     int64
 12  신항4부두   31 non-null     int64
 13  신항5부두   31 non-null     int64
 14  다목적부두등  31 non-null     int64
dtypes: int64(15)
memory usage: 3.8 KB
None
             년도             합계         자성대부두         신선대부두          감만부두  \
count    31.000         31.000        31.000        31.000        31.000
mean  2,009.000 13,968,781.839 1,593,494.387 1,913,993.613 1,560,014.161
std       9.092  6,999,840.852   534,312.037   702,625.486   818,635.394
min   1,994.000     48,140.000         0.000         0.000         0.000
25%   2,001.500  8,763,491.500 1,404,957.000 1,471,135.500 1,229,097.500
50%   2,009.000 13,454,506.000 1,729,414.000 2,054,646.000 1,498,394.000
75%   2,016.500 19,981,102.000 1,920,802.000 2,388,699.500 1,999,389.000
max   2,024.000 24,402,022.000 2,275,402.000 2,813,335.000 2,862,251.000

             우암부두        감천한진         신감만부두          일반부두         신항1부두  \
count      31.000      31.000        31.000        31.000        31.000
mean  274,748.871 174,349.484   750,659.968 1,291,685.581 1,123,327.839
std   260,821.050 237,488.157   485,674.603 1,102,135.980 1,169,519.214
min         0.000       0.000         0.000    48,140.000         0.000
25%       433.500     623.000   234,139.500   304,167.000         0.000
50%   316,902.000   1,880.000   976,348.000   678,177.000   701,124.000
75%   540,690.000 441,369.000 1,126,288.000 2,575,833.500 2,419,781.000
max   640,339.000 574,824.000 1,250,360.000 3,202,849.000 3,018,315.000

              신항2부두         신항3부두         신항4부두         신항5부두        다목적부두등
count        31.000        31.000        31.000        31.000        31.000
mean  2,123,785.742 1,238,135.935 1,027,237.548   767,662.226   129,686.484
std   2,238,415.343 1,285,070.893 1,118,048.373 1,002,711.544   359,132.660
min           0.000         0.000         0.000         0.000         0.000
25%           0.000         0.000         0.000         0.000         0.000
50%     796,830.000   922,419.000         0.000         0.000       214.000
75%   4,578,868.500 2,511,853.500 2,202,690.500 1,740,969.000    50,448.500
max   5,501,091.000 3,076,160.000 2,560,274.000 2,496,909.000 1,844,868.000

In [32]:
pd.DataFrame({
    '자료형': df.dtypes.astype('str'),
    '비결측 수': df.notna().sum(),
    '결측 수': df.isna().sum(),
    '결측률(%)': df.isna().mean()*100,
    '고유값 수': df.nunique(dropna=True)

})

          자료형  비결측 수  결측 수  결측률(%)  고유값 수
년도      int64     31     0   0.000     31
합계      int64     31     0   0.000     31
자성대부두   int64     31     0   0.000     30
신선대부두   int64     31     0   0.000     31
감만부두    int64     31     0   0.000     29
우암부두    int64     31     0   0.000     26
감천한진    int64     31     0   0.000     29
신감만부두   int64     31     0   0.000     24
일반부두    int64     31     0   0.000     31
신항1부두   int64     31     0   0.000     20
신항2부두   int64     31     0   0.000     19
신항3부두   int64     31     0   0.000     17
신항4부두   int64     31     0   0.000     16
신항5부두   int64     31     0   0.000     15
다목적부두등  int64     31     0   0.000     18

In [34]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
년도,31.000,"2,009.000",9.092,"1,994.000","2,001.500","2,009.000","2,016.500","2,024.000"
합계,31.000,"13,968,781.839","6,999,840.852","48,140.000","8,763,491.500","13,454,506.000","19,981,102.000","24,402,022.000"
자성대부두,31.000,"1,593,494.387","534,312.037",0.000,"1,404,957.000","1,729,414.000","1,920,802.000","2,275,402.000"
신선대부두,31.000,"1,913,993.613","702,625.486",0.000,"1,471,135.500","2,054,646.000","2,388,699.500","2,813,335.000"
감만부두,31.000,"1,560,014.161","818,635.394",0.000,"1,229,097.500","1,498,394.000","1,999,389.000","2,862,251.000"
우암부두,31.000,"274,748.871","260,821.050",0.000,433.500,"316,902.000","540,690.000","640,339.000"
감천한진,31.000,"174,349.484","237,488.157",0.000,623.000,"1,880.000","441,369.000","574,824.000"
신감만부두,31.000,"750,659.968","485,674.603",0.000,"234,139.500","976,348.000","1,126,288.000","1,250,360.000"
일반부두,31.000,"1,291,685.581","1,102,135.980","48,140.000","304,167.000","678,177.000","2,575,833.500","3,202,849.000"
신항1부두,31.000,"1,123,327.839","1,169,519.214",0.000,0.000,"701,124.000","2,419,781.000","3,018,315.000"
신항2부두,31.000,"2,123,785.742","2,238,415.343",0.000,0.000,"796,830.000","4,578,868.500","5,501,091.000"
신항3부두,31.000,"1,238,135.935","1,285,070.893",0.000,0.000,"922,419.000","2,511,853.500","3,076,160.000"
신항4부두,31.000,"1,027,237.548","1,118,048.373",0.000,0.000,0.000,"2,202,690.500","2,560,274.000"
신항5부두,31.000,"767,662.226","1,002,711.544",0.000,0.000,0.000,"1,740,969.000","2,496,909.000"
다목적부두등,31.000,"129,686.484","359,132.660",0.000,0.000,214.000,"50,448.500","1,844,868.000"

In [50]:
df[['년도','합계']]

      년도        합계
0   1994     48140
1   1995     59775
2   1996   4809217
3   1997   5246646
4   1998   5701360
5   1999   6555803
6   2000   7729508
7   2001   8073125
8   2002   9453858
9   2003  10408238
10  2004  11492416
11  2005  11843166
12  2006  12038607
13  2007  13265127
14  2008  13454506
15  2009  11965485
16  2010  14158214
17  2011  16076550
18  2012  17046181
19  2013  17686100
20  2014  18683288
21  2015  19468725
22  2016  19456292
23  2017  20493479
24  2018  21662573
25  2019  21992001
26  2020  21823997
27  2021  22706131
28  2022  22078196
29  2023  23153511
30  2024  24402022

In [49]:
stable = df[df['년도'].ge(1996)] 

stable

,년도,합계,자성대부두,신선대부두,감만부두,우암부두,감천한진,신감만부두,일반부두,신항1부두,신항2부두,신항3부두,신항4부두,신항5부두,다목적부두등
2,1996,4809217,1673341,1302513,0,21171,0,0,1812192,0,0,0,0,0,0
3,1997,5246646,1757757,1413847,23,316902,11848,0,1746269,0,0,0,0,0,0
4,1998,5701360,1096650,1121949,891424,281571,348910,0,1960856,0,0,0,0,0,0
5,1999,6555803,995119,1160577,1458472,355761,449766,0,2136108,0,0,0,0,0,0
6,2000,7729508,1304180,1281914,1887418,342486,403174,0,2510336,0,0,0,0,0,0
7,2001,8073125,1272333,1319812,1922622,447704,432972,0,2677682,0,0,0,0,0,0
8,2002,9453858,1534639,1528424,2261533,502460,504269,481202,2641331,0,0,0,0,0,0
9,2003,10408238,1584468,1786165,2546451,533298,512285,745613,2699958,0,0,0,0,0,0
10,2004,11492416,1825568,1994931,2723891,549967,548111,976348,2873600,0,0,0,0,0,0
11,2005,11843166,2126618,1962001,2862251,577392,497693,1098625,2718586,0,0,0,0,0,0
12,2006,12038607,2212473,2054646,2558765,548082,503673,1144700,2778554,237714,0,0,0,0,0
13,2007,13265127,2275402,2400910,2842963,531409,574824,1250360,2809608,446121,133530,0,0,0,0
14,2008,13454506,2103063,2282941,2722509,564691,556152,1210606,3202849,518839,292775,0,0,0,81
15,2009,11965485,1898370,2655797,2076156,552024,43283,1166042,888759,965591,796830,922419,0,0,214
16,2010,14158214,1581497,2688412,1873341,612496,1186,1228348,707637,701124,2389293,1533368,837088,0,4424
17,2011,16076550,1479816,2570889,1803991,640339,187,1240871,661029,928205,3213108,1952505,1576776,21,8813
18,2012,17046181,1286489,2372698,1628853,569922,468,1141941,603117,1220233,3280017,2442636,1988675,459969,51163
19,2013,17686100,1366534,1744861,1465206,514920,264,1032732,598215,1747307,3299457,2375614,2391890,1099366,49734
20,2014,18683288,1476998,2190665,1136003,46862,2579,1185608,678177,1712729,3895202,2467741,2552383,1305610,32731
21,2015,19468725,1729414,2015853,1132395,2718,3234,1110635,596629,2420860,4296221,2555966,2320661,1261535,22604
22,2016,19456292,1867428,1954293,1171826,2465,1880,1069650,527801,2418702,4626435,1925545,2322166,1541859,26242
23,2017,20493479,2073695,2260708,1286369,538,1146,943275,447729,2689256,4531302,2219402,2069198,1940079,30782
24,2018,21662573,1926182,2490203,1287910,1476,624,970504,320429,2477785,4938446,2770535,2061131,2269682,147666
25,2019,21992001,1923735,2404009,1444404,329,1427,1008637,178400,2295359,5501091,2783576,2167478,2119075,164481
26,2020,21823997,1826714,2307478,1509062,232,1855,1033422,166895,2743856,4837172,2954267,2110318,2131414,201312
27,2021,22706131,1982803,2376489,1498394,0,1012,1016701,287905,2737054,5086577,2939071,2237903,2315414,226808
28,2022,22078196,1917869,2341909,1424086,0,518,890661,255386,2684136,4827307,2672948,2257767,2433623,371986
29,2023,23153511,1855791,2534951,1400828,0,622,855699,196556,2859977,4934689,2790461,2390656,2496909,836372
30,2024,24402022,1443380,2813335,1543293,0,872,468279,252367,3018315,4957906,3076160,2560274,2422973,1844868

In [52]:
stable = df[['년도', '합계']].copy()
stable['증감률(%)'] = stable['합계'].pct_change() * 100
stable = stable[stable['년도'] >= 1997]
stable[['년도', '합계', '증감률(%)']]

      년도        합계  증감률(%)
3   1997   5246646   9.096
4   1998   5701360   8.667
5   1999   6555803  14.987
6   2000   7729508  17.903
7   2001   8073125   4.446
8   2002   9453858  17.103
9   2003  10408238  10.095
10  2004  11492416  10.417
11  2005  11843166   3.052
12  2006  12038607   1.650
13  2007  13265127  10.188
14  2008  13454506   1.428
15  2009  11965485 -11.067
16  2010  14158214  18.325
17  2011  16076550  13.549
18  2012  17046181   6.031
19  2013  17686100   3.754
20  2014  18683288   5.638
21  2015  19468725   4.204
22  2016  19456292  -0.064
23  2017  20493479   5.331
24  2018  21662573   5.705
25  2019  21992001   1.521
26  2020  21823997  -0.764
27  2021  22706131   4.042
28  2022  22078196  -2.765
29  2023  23153511   4.870
30  2024  24402022   5.392

# 장기성장 
1997년부터 꾸준히 성장, 2009년에 하락

In [89]:
df = pd.read_csv('Forecast.csv', encoding='cp949')
df.head()

monthly = (df.groupby('연월')['물동량'].sum().reset_index())

monthly

          연월           물동량
0    1992-01   196,572.000
1    1992-02   195,572.000
2    1992-03   242,358.000
3    1992-04   229,614.000
4    1992-05   222,359.000
..       ...           ...
393  2024-10 2,049,390.750
394  2024-11 1,998,100.750
395  2024-12 2,067,420.250
396  2025-01 2,126,084.750
397  2025-02 1,963,543.500

[398 rows x 2 columns]

In [64]:
monthly = (
df.groupby(['연도', '월'])['물동량'] .sum() .reset_index()
)

monthly_avg = (monthly.groupby('월')['물동량'].mean().reset_index()
)

monthly_avg['증감률(%)'] = monthly_avg['물동량'].pct_change() * 100

monthly_avg

     월           물동량  증감률(%)
0    1 1,104,991.904     NaN
1    2 1,029,116.728  -6.867
2    3 1,161,058.583  12.821
3    4 1,143,037.447  -1.552
4    5 1,156,498.735   1.178
5    6 1,122,079.235  -2.976
6    7 1,148,085.061   2.318
7    8 1,111,875.970  -3.154
8    9 1,088,755.848  -2.079
9   10 1,140,525.424   4.755
10  11 1,129,007.659  -1.010
11  12 1,142,815.598   1.223

In [66]:
avg = monthly_avg['물동량'].mean()

monthly_avg['평균차이'] = monthly_avg['물동량'] - avg

monthly_avg

     월           물동량  증감률(%)        평균차이
0    1 1,104,991.904     NaN -18,162.112
1    2 1,029,116.728  -6.867 -94,037.288
2    3 1,161,058.583  12.821  37,904.567
3    4 1,143,037.447  -1.552  19,883.431
4    5 1,156,498.735   1.178  33,344.719
5    6 1,122,079.235  -2.976  -1,074.781
6    7 1,148,085.061   2.318  24,931.045
7    8 1,111,875.970  -3.154 -11,278.046
8    9 1,088,755.848  -2.079 -34,398.168
9   10 1,140,525.424   4.755  17,371.408
10  11 1,129,007.659  -1.010   5,853.643
11  12 1,142,815.598   1.223  19,661.582

In [67]:
monthly_avg['차이율(%)'] = (monthly_avg['평균차이'] / avg * 100).round(2)
monthly_avg

     월           물동량  증감률(%)        평균차이  차이율(%)
0    1 1,104,991.904     NaN -18,162.112  -1.620
1    2 1,029,116.728  -6.867 -94,037.288  -8.370
2    3 1,161,058.583  12.821  37,904.567   3.370
3    4 1,143,037.447  -1.552  19,883.431   1.770
4    5 1,156,498.735   1.178  33,344.719   2.970
5    6 1,122,079.235  -2.976  -1,074.781  -0.100
6    7 1,148,085.061   2.318  24,931.045   2.220
7    8 1,111,875.970  -3.154 -11,278.046  -1.000
8    9 1,088,755.848  -2.079 -34,398.168  -3.060
9   10 1,140,525.424   4.755  17,371.408   1.550
10  11 1,129,007.659  -1.010   5,853.643   0.520
11  12 1,142,815.598   1.223  19,661.582   1.750

# 계절성
전반적으로 봄철 증가 후 여름 말(8~9월)에 감소하는 계절적 패턴